#!/bin/bash

show_machine_info() {
    tput setaf 1
    echo -e "\nTerminal session started on $(date "+%A %B %-d at %H:%M" | sed 's/ 1 / 1st /; s/ 2 / 2nd /; s/ 3 / 3rd /; s/ 21 / 21st /; s/ 22 / 22nd /; s/ 23 / 23rd /; s/ 31 / 31st /; s/ \([4-9]\|1[0-9]\|2[04-9]\|30\) / \1th /'):"
    tput setaf 202
    echo -e "\nMachine Information:"
    echo "---------------------"
    tput setaf 170
    echo -e "System:"
    tput setaf 39
    hostnamectl
    tput setaf 170
    echo "CPU:"
    tput setaf 39
    lscpu | grep "Model name" | sed 's/Model name://g; s/  */ /g'
    tput setaf 170
    echo -e "Memory:"
    tput setaf 39
    sudo dmidecode -t memory | grep Size
    sudo dmidecode -t memory | grep -A 20 "Memory Device" | grep -E "Size:|Manufacturer:|Part Number:|Serial Number:"
    tput setaf 202
    echo "---------------------"
}

show_network_info() {
    tput setaf 202
    echo -e "\nNetwork Information:"
    echo "---------------------"
    tput setaf 48
    echo "IP Addresses:"
    ip a | grep 192
    # echo "MAC Address: $(ifconfig en0 | awk '/ether/{print $2}')"
    # echo "DNS Servers:"
    # scutil --dns | grep 'nameserver\[[0-9]*\]' | awk '{print $3}'
    tput setaf 202
    echo "---------------------"
}

show_user_info() {
    tput setaf 202
    echo -e "\nUser Information:"
    echo "---------------------"
    tput setaf 39
    echo "Current User: $(whoami)"
    echo "Home Directory: $HOME"
    echo "Shell: $SHELL"
    echo "Logged In Users:"
    who
    tput setaf 202
    echo "---------------------"
}

show_system_uptime() {
    tput setaf 202
    echo -e "\nSystem Uptime:"
    echo "---------------------"
    tput setaf 48
    uptime
    tput setaf 202
    echo "---------------------"
}

show_disk_usage() {
    tput setaf 202
    echo -e "\nDisk Usage:"
    echo "---------------------"
    tput setaf 39
    df -h
    tput setaf 202
    echo "---------------------"
}

show_memory_usage() {
    tput setaf 202
    echo -e "\nMemory Usage:"
    echo "---------------------"
    tput setaf 48
    free --si -h
    tput setaf 202
    echo "---------------------"
}

show_process_info() {
    tput setaf 202
    echo -e "\nTop 8 Memory Consuming Processes:"
    echo "---------------------"
    tput setaf 39
    ps aux | sort -nrk 4 | head -n 9 | awk '{NF=11; print}'
    tput setaf 202
    echo "---------------------"
}

show_all_info() {
    show_machine_info
    show_network_info
    show_user_info
    show_system_uptime
    show_disk_usage
    show_memory_usage
    show_process_info
    tput sgr0
}

if [ $# -eq 0 ]; then
    show_all_info
else
    for arg in "$@"; do
        case $arg in
            --machine|-m) show_machine_info ;;
            --network|-n) show_network_info ;;
            --user|-u) show_user_info ;;
            --uptime|-t) show_system_uptime ;;
            --disk|-d) show_disk_usage ;;
            --memory|-M) show_memory_usage ;;
            --process|-p) show_process_info ;;
            --all|-a) show_all_info ;;
            *) echo "Unknown option: $arg" ;;
        esac
    done
fi

exit 0
